// <auto-generated />
namespace H.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class KsData : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KsData));
        
        string IMigrationMetadata.Id
        {
            get { return "202005271605035_KsData"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
